### ISSUE TITLE
<iframe>

### ISSUE THREAD

**Issue by sswwyyaatt** [Signmark/ATMTA-Station#102]
**Описание проблемы**:
При использовании <iframe> в чате, происходит некоторое дерьмо.

**Что должно было произойти**: 
Нормально обработанный iframe

**Что произошло вместо этого**:
Я положил почти 10 человек.

**Почему это плохо/Какие последствия этого:**
Пизда ивенту, бомбление пуканов.

**Детальное описание как повторить возникновение проблемы**:
<iframe src="http://niceme.me" style="border:0px #FFFFFF none;" name="myiFrame" scrolling="no" frameborder="1" marginheight="0px" marginwidth="0px" height="60px" width="468px"></iframe>

Вот это в чат, и ожидай

**Что-нибудь еще что может помочь (какой был режим, была ли у вас роль, какие-то особенности и т.д.)**: 

Все, что может нам помочь.
Ничего

**Comment by ITBlackwood** [comment]
Пока что единственный способ который я вижу чтобы исправить эту проблему - убрать возможность встраивания html в чате.

**Comment by Signmark** [comment]
@ITBlackwood убирать iframe через санитайз текста

**Comment by Signmark** [comment]
Является ли свят админом? Имеет ли он хотя бы флаг +ADMIN? потому что гунчат должен обрабатывать хтмл только от админов

**Comment by sswwyyaatt** [comment]
Никак нет, комрад

11 дек. 2016 г. 10:33 ПП пользователь "Signmark" <notifications@github.com>
написал:
>
> Является ли свят админом? Имеет ли он хотя бы флаг +ADMIN? потому что
гунчат должен обрабатывать хтмл только от админов

**Comment by Signmark** [comment]
https://github.com/d3athrow/vgstation13/pull/11006
ну вообще я думал что вроде бы сделал этот фикс
но теперь я не уверен

**Comment by Signmark** [comment]
https://github.com/ParadiseSS13/Paradise/pull/5450
https://github.com/ParadiseSS13/Paradise/pull/3942
не понимаю в чем проблема, надо поставить фикс от вг

**Comment by sswwyyaatt** [comment]
Могу для повторной проверки запустить ещё один сервер, на другом порту. 
Нужно будет зайти с нового byond аккаунта.

**Comment by Signmark** [comment]
![image](https://cloud.githubusercontent.com/assets/19763675/21082749/accd19d4-c003-11e6-8443-5ddcdf912d84.png)
сравните функцию хайлайта хтмл на вг
![image](https://cloud.githubusercontent.com/assets/19763675/21082760/bf70545c-c003-11e6-8fd3-6e602f06d8c2.png)
и на парадайзе

**Comment by sswwyyaatt** [comment]
Могу чем то ещё помочь?

**Comment by sswwyyaatt** [comment]
Короче. 
Вот этот файл

Вот этот кусок кода goon\browserassets\js\browserOutput.JS

> # //Shit fucking piece of crap that doesn't work god fuckin damn it

function linkify(text) {
	var rex = /((?:<a|<iframe|<img)(?:.*?(?:src="|href=").*?))?(?:(?:https?:\/\/)|(?:www\.))+(?:[^ ]*?\.[^ ]*?)+[-A-Za-z0-9+&@#\/%?=~_|$!:,.;]+/ig;
	return text.replace(rex, function ($0, $1) {
		if(/^https?:\/\/.+/i.test($0)) {
			return $1 ? $0: '<a href="'+$0+'">'+$0+'</a>';
		}
		else {
			return $1 ? $0: '<a href="http://'+$0+'">'+$0+'</a>';
		}
	});
}

**Comment by Signmark** [comment]
aye
