### ISSUE TITLE
ГДЕ МОЯ СЛАСТЕНА

### ISSUE THREAD

**Issue by Signmark** [Signmark/ATMTA-Station#106]
Сластена не кликается в лоадауте

**Comment by sswwyyaatt** [comment]
[03:08:55] ## Runtime in preferences.dm,1114: Cannot read # null.display_name
   proc name: process link (/datum/preferences/proc/process_link)
   usr: Sswwyyaatt (sswwyyaatt) (/mob/new_player)
   usr.loc: The floor (8,174,2) (/turf/unsimulated/floor)
   src: /datum/preferences (/datum/preferences)
   call stack:
   /datum/preferences (/datum/preferences): process link(Sswwyyaatt (/mob/new_player), /list (/list))
   Sswwyyaatt (/client): Topic("_src_=prefs;preference=gear;to...", /list (/list), null)

**Comment by ITBlackwood** [comment]
*scream
