### ISSUE TITLE
Бутылки

### ISSUE THREAD

**Issue by sswwyyaatt** [Signmark/ATMTA-Station#108]
**Описание проблемы**:
В пермабриге нельзя сажать на бутылки.

**Что должно было произойти**: 
Сб сажает на бутылку!

**Что произошло вместо этого**:
Сб НЕ сажает на бутылку!
**Почему это плохо/Какие последствия этого:**
Сб сажает на бутылку, из за этого дклассу скучно.

**Детальное описание как повторить возникновение проблемы**:
   -   -   -

**Что-нибудь еще что может помочь (какой был режим, была ли у вас роль, какие-то особенности и т.д.)**: 
Все, что может нам помочь.

**Comment by sswwyyaatt** [comment]
Fix

Почему это плохо/Какие последствия этого:
Сб не сажает на бутылку, из за этого дклассу скучно.

**Comment by ITBlackwood** [comment]
Смешно, но лишено смысла. Клоз.
