### ISSUE TITLE
Zabivaka set

### ISSUE THREAD

**Issue by sswwyyaatt** [Signmark/ATMTA-Station#109]
**Описание проблемы**:
Нету сэта забиваки

**Что должно было произойти**: 
Кто то нарисовал сэт забиваки

**Что произошло вместо этого**:
Никто не нарисовал сэт забиваки

**Почему это плохо/Какие последствия этого:**
Нет забиваки, гроб гроб, станция пидор. 
Смерть мерзкая от сс13

**Детальное описание как повторить возникновение проблемы**:
-

**Что-нибудь еще что может помочь (какой был режим, была ли у вас роль, какие-то особенности и т.д.)**: 
Все, что может нам помочь.
Удачи, здоровья, хорошего настроения.

**Comment by ITBlackwood** [comment]
За донат нарисую и добавлю.

**Comment by ITBlackwood** [comment]
Хотя нет, не нарисую.

**Comment by Signmark** [comment]
фурсьюты это зло их надо сжигать
