### ISSUE TITLE
А вообще где новая детективка,карта,медбей,фикс багов с гунлайтм

### ISSUE THREAD

**Issue by KyubeyQB** [Signmark/ATMTA-Station#192]
**Описание проблемы**:
А вообще где новая криминалистика?Где карта?Где реворк операций в меде(из бея воооооооот)?А еще новые правила,а то ваш хай рп не оч.А еще реворк вайтлиста

**Что должно было произойти**: 
It will make station great again

**Comment by sswwyyaatt** [comment]
# Хууй

**Comment by Signmark** [comment]
и где рул34 по сластене

**Comment by Signmark** [comment]
@KyubeyQB
пиздуй вики писать
