### ISSUE TITLE
Adeptus Mechanicus robes

### ISSUE THREAD

**Issue by Valnaver** [Signmark/ATMTA-Station#194]
Адептус Механикус — имперская организация технологов,Адептус Механикус имеют жизненно важное значение для Империума, занимаясь созданием и обслуживанием наиболее совершенных технологий Империума...Я понимаю что технологии РнД не особо важные во вселенной и жизни стацнии,но можно научному отделу и роботехникам всё же выдать возможность брать робу в лоудауты?

**Comment by ITBlackwood** [comment]
Нет, это уже чрезмерное вахоебство. Ничего плохого о вархаммере конечно не думаю, но РнД в красных робах... Глупая картина.

**Comment by Valnaver** [comment]
Но она же создана для роботиста...

**Comment by sswwyyaatt** [comment]
Закрыто

31 дек. 2016 г. 3:25 ПП пользователь "Valnaver" <notifications@github.com>
написал:

**Comment by Signmark** [comment]
Это косметический костюм за карму и не более

**Comment by Valnaver** [comment]
Костюм за карму доступный только инженеру...Шито поделать,нет так нет.
