### ISSUE TITLE
Шаттл и стулья.

### ISSUE THREAD

**Issue by Dydna** [Signmark/ATMTA-Station#199]
При полёте на шаттле (время прибытия или отбытия) даже если персонаж сидит на стуле он с него падает.

Следовательно должно произойти то, чтобы он с него не падал.

**Comment by ITBlackwood** [comment]
Багфикс будет со следующей синхронизацией.

**Comment by Lianovskiy** [comment]
Куда завершено бля? Как падали со стульев, так и падаем.
