### ISSUE TITLE
Мама я сгорел и голодные псы...

### ISSUE THREAD

**Issue by sswwyyaatt** [Signmark/ATMTA-Station#202]
**Описание проблемы**:
Плазмамен дкласса

**Что должно было произойти**: 
Ничего странного или необычного

**Что произошло вместо этого**:
Плазмамiн сгорiл к хуям
**Почему это плохо/Какие последствия этого:**
Хмм. Огонь в дклассе? Обожгутся зэки. 

**Детальное описание как повторить возникновение проблемы**:
Сделоца плазмоменом, зайти за дкласс.
**Что-нибудь еще что может помочь (какой был режим, была ли у вас роль, какие-то особенности и т.д.)**: 
3 часа утра, мы в щщи

Все, что может нам помочь.
Удачи, здоровья. Держитесь там!

**Comment by Signmark** [comment]
плазмаменов за дкласс не бывает это все сказки
