### ISSUE TITLE
Множество штук, которые должны улучшить игру по моему личному мнению.

### ISSUE THREAD

**Issue by Lianovskiy** [Signmark/ATMTA-Station#210]
1) Хочу, чтобы женским персонажам рандомно генерировался размер груди, также как мужским - размер пениса. Можно от a до dd, или цифрами. В идеале хотелось бы отдельные спрайты и выбор в настройке персонажа.

2) В космозакон требуется завезти статью об "бесчеловечном отношении с боргами". Игра за боргов - это ад, педали ебут во все щели за неисполнение законов, а персонал относится хуже, чем к д-классовцам.

3) Почините факс-машины. Они всё также не могут отсылать сообщения на цк (по сведениям игроков, играющих за АВД), также, коммуникационные консоли.

4) Почините баг с падением привязанного со стула при отлёте шатола.

5)А, также хотелось бы, чтобы эмоция "мурчать" у таяр могла проигрываться командой, типа *scream или *cry
Предлагаю *purr

6)Также хочу, чтобы при надевании брони и шлема крестоноста появлялось действие "Деус вульт". Проигрывает деус вульт, как хальтер. Также хотелось бы, чтобы добавили кадило, кисточку для освещения и рефиллер святой воды.

**Comment by Lianovskiy** [comment]
А, также хотелось бы, чтобы эмоция "мурчать" у таяр могла проигрываться командой, типа *scream или *cry
Предлагаю *purr

**Comment by Lianovskiy** [comment]
Также хочу, чтобы при надевании брони и шлема крестоноста появлялось действие "Деус вульт". Проигрывает деус вульт, как хальтер. Также хотелось бы, чтобы добавили кадило, кисточку для освещения и рефиллер святой воды.

**Comment by Dydna** [comment]
2 чая этому господину.Нам нужны Факсы для связи с ЦК.

**Comment by Signmark** [comment]
Оформи пожалуйста все вопросы отдельными темами, так как они закрываются автоматически с выходом фикса. 6 тем по 1 вопросу > 1 темы с 6 вопросами. Тем более что сейчас я разберу эти вопросы и их станет вдвое меньше:
1)от нас ушел человек, который этим занимался (хонк), а оставшиеся не возьмутся ни за что
2)не играй за боргов ни - ког - да, никто так и не придумал боргам нормального игрового процесса, отдав роль на отыгрыш ПО АР ПИ (это никогда не шло на пользу ни одной профе - никто не играет на РП-профах ради РП, никто не обращает внимание на РП-аспект борга, простейший способ получить гарантированный бан на любом сервере - постоянно играть на боргах и ИИ, или просто часто взаимодействовать с боргами.) Ей богу, я бы лучше отдал киборгов и ИИ под управление компьютера, потратив месяц-два на написание поведенческого алгоритма и угробив половину ресурсов сервера на их работу, чем вот так вот отдать наотмашь игроку.

Однако статья нужна, **поэтому отведи вопросу 2 отдельную тему**

3)Это не баг, факсы АВД не имеют связи с ЦК, только командование и представитель.
4)дублирование #199
5)**в отдельную тему**
6)**в отдельную тему**

Итого жду **3 отдельных темы**

**Comment by Valnaver** [comment]
Напомните мне почему ии не может имять связи с цк?

**Comment by Signmark** [comment]
Здесь речь про ИИ?

**Comment by Valnaver** [comment]
В целом,я считаю не много маразмом что агент внутренних дел и ии не могут в связь с цк.Так же как и из глав только капитан и хос имеют право менять код...

**Comment by Lianovskiy** [comment]
Пиши ишшу тогда на это

**Comment by Dydna** [comment]
если я не ошибаюсь, но даже у представителя нет связи с цк
