### ISSUE TITLE
У боргов тоже есть бинарные чувства!

### ISSUE THREAD

**Issue by Lianovskiy** [Signmark/ATMTA-Station#212]
В космозакон требуется завезти статью об "бесчеловечном отношении с боргами". Игра за боргов - это ад, педали ебут во все щели за неисполнение законов, а персонал относится хуже, чем к д-классовцам.

И нет, сигнмарк, я как-то нормально справляюсь с игровым процессом за боргов. Борги тоже люди! Просто без рук. И с заканчивающейся батареей. Но это не важно! Важно то, что они отлично заменяют любой недостающий персонал при наличии роботиста/рд/д-классовца с доступом.

**Comment by ITBlackwood** [comment]
Борги - не более чем имущество станции. Чувств у них нет.
Статья за их порчу - вандализм.
