### ISSUE TITLE
Ожирение таяр

### ISSUE THREAD

**Issue by Lianovskiy** [Signmark/ATMTA-Station#214]
**Описание проблемы**:
В пресете нельзя выставить болезнь "жирнота". Написано, что таяры НЕ могут быть толстыми, но, тем не менее, переев можно стать жирным.

**Что должно было произойти**: 
Выпилите таярам способность жиреть. Совсем.

**Comment by ITBlackwood** [comment]
Разве это не сделает таяр дисбалансными? Это немного некорректно, учитывая что строение их пищеварения и обмена веществ идентично людскому. Может принимать на работу уже жирных таяр нельзя? И ничто не мешает им набрать вес будучи на станции.

**Comment by Lianovskiy** [comment]
Ничто не делает ни одну расу дисбалансной (спасибо шейку потери веса), но мне просто непонятно, как оно должно работать по лору. 

Хотя говорят, что сколько вульпа не корми, а он всё худым будет, но этого я проверить не могу.

**Comment by ITBlackwood** [comment]
В общем, не вижу особой проблемы здесь. Клоз.
