### ISSUE TITLE
Скорейшее допиливание вики.

### ISSUE THREAD

**Issue by Lianovskiy** [Signmark/ATMTA-Station#216]
Я считаю, что нужно опять разрешить редактирование вики АТМТЫ всем желающим. Так скорость заполнения статей увеличится в разы, а Фёдор освободится для кодинга.

**Comment by ITBlackwood** [comment]
Фёдор и так занят кодингом, по большей части. 

Я закрыл доступ для редактирования по той причине что качество заполнения и дезинформация создают беспорядок на википедии. Сейчас помимо меня есть еще 5 человек которые могут редактировать вики. И они напрямую по моим поручениям пишут статьи, которые я своевременно проверяю. 

Вики это вообще больная тема. Меня настолько корежит от того что к ней еще кто-то прикасается, и делает порой все настолько КРИВО что я хочу писать ее вообще один. Паранойя у меня, так сказать. Учитывая занятость, это не представляется возможным.  

Надеюсь я ответил на вопрос предельно ясно.

**Comment by Lianovskiy** [comment]
Мне, конечно, такой подход не нравится, ведь можно было бы попросту составить какой-нибудь небольшой мануал по редактированию, да и вообще я сторонник перехода количества в качество, а не медленного заполнения, но палка редактора не у меня.
