### ISSUE TITLE
Life.dm

### ISSUE THREAD

**Issue by ITBlackwood** [Signmark/ATMTA-Station#54]
**Описание проблемы**:
Рантайм. 
Runtime in life.dm,1117: Cannot read null.assigned_role

**Что должно было произойти**: 
Его быть не должно. 

**Что произошло вместо этого**:
Он есть. 

**Почему это плохо/Какие последствия этого:**
Появляется часто. Каждые 2-3 минуты, даже чаще. 

**Что-нибудь еще что может помочь (какой был режим, была ли у вас роль, какие-то особенности и т.д.)**: 
Даже в эксту возникает.

**Comment by Signmark** [comment]
https://github.com/Signmark/ATMTA-Station/commit/08a57d8612b6af793d345317137f269be8c478eb
пофикшено
