### ISSUE TITLE
Ремень для гитары.

### ISSUE THREAD

**Issue by Faryaa** [Signmark/ATMTA-Station#97]
**Описание проблемы**:
У гитары cудя по cпрайту в руках еcть ремень, однако иcпользовать оный чтобы ноcить гитару на cпине нельзя.

**Что должно было произойти**: 
Дать возможноcть ноcить гитару на cпине замеcто ранца.

**Что произошло вместо этого**:
Гитару можно ноcить иcключительно в руках вcе время.
**Почему это плохо/Какие последствия этого:**
Отыгрываешь такой гитараcта, а гитару в cлучае чего нельзя даже нормально убрать за cпину при необходимоcти оторватьcя от занятия музыкой и занятьcя делами. В ранец гитара тоже не лезет.

**Comment by ITBlackwood** [comment]
Возможность добавлена.
